services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/data/
    env_file:
      - ./.env
  api:
    build: .
    entrypoint: ./entrypoint.sh
    restart: always
    volumes:
      - type: bind
        source: .
        target: /home/app/www
    env_file:
      - ./.env
    environment:
      - MARIADB_HOST=db
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_data:
