services:
  api:
    build: .
    command: uvicorn "src.main:app" --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - type: bind
        source: .
        target: /home/app/www
    env_file:
      - ./.env
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql/data/
    env_file:
      - ./.env
    tty: true

volumes:
  db_data:
